import type { Metadata } from "next";
import "./globals.css";
import MainNav from "@/components/main-nav";

export const metadata: Metadata = {
	title: "Ticketing System",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<header className="flex flex-col items-center border-b mb-5 px-5 py-3">
					<div className="max-w-6xl w-full">
						<MainNav />
					</div>
				</header>
				<main className="flex flex-col items-center">
					<div className="max-w-6xl w-full">{children}</div>
				</main>
			</body>
		</html>
	);
}
