import './globals.css';

import type { Metadata } from 'next';

import MainNav from '@/components/main-nav';
import { ThemeProvider } from '@/providers/theme-provider';

export const metadata: Metadata = {
  title: 'Ticketing System',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
        >
          <header className="mb-5 flex flex-col items-center border-b px-5 py-3">
            <div className="w-full max-w-6xl">
              <MainNav />
            </div>
          </header>
          <main className="flex flex-col items-center">
            <div className="w-full max-w-6xl">{children}</div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
